// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvKca3peZapPH6AIBFdGXSyxIQ3efjLxk',
    appId: '1:206342411353:web:c57df349c9b733703b4d48',
    messagingSenderId: '206342411353',
    projectId: 'evently-mobile-application',
    authDomain: 'evently-mobile-application.firebaseapp.com',
    storageBucket: 'evently-mobile-application.firebasestorage.app',
    measurementId: 'G-RJ7GSSED3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiU4xhpOX-CRNDsaL6pMtWOjgceyzjnNQ',
    appId: '1:206342411353:android:e13c6a62bacbb3dc3b4d48',
    messagingSenderId: '206342411353',
    projectId: 'evently-mobile-application',
    storageBucket: 'evently-mobile-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY43FjGE8TthBrLCkhYI5vJdpLI8eWe_k',
    appId: '1:206342411353:ios:2e81963d1ffe18d43b4d48',
    messagingSenderId: '206342411353',
    projectId: 'evently-mobile-application',
    storageBucket: 'evently-mobile-application.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY43FjGE8TthBrLCkhYI5vJdpLI8eWe_k',
    appId: '1:206342411353:ios:2e81963d1ffe18d43b4d48',
    messagingSenderId: '206342411353',
    projectId: 'evently-mobile-application',
    storageBucket: 'evently-mobile-application.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvKca3peZapPH6AIBFdGXSyxIQ3efjLxk',
    appId: '1:206342411353:web:4feeb392f91d9cb03b4d48',
    messagingSenderId: '206342411353',
    projectId: 'evently-mobile-application',
    authDomain: 'evently-mobile-application.firebaseapp.com',
    storageBucket: 'evently-mobile-application.firebasestorage.app',
    measurementId: 'G-0187Z4TF35',
  );
}
